const nodemailer = require('nodemailer');
// const pool = require('../Model/DB_connection');
const dotenv = require("dotenv");

dotenv.config();

exports.sendMail = async (result) => {
    try {
        // Construct the email content with a colorful, modern design
        let mailContent = `
        <html>
        <head>
            <style>
                body {
                    font-family: 'Arial', sans-serif;
                    margin: 0;
                    padding: 0;
                    background-color: #f4f4f4;
                    color: #333;
                }
                .email-wrapper {
                    max-width: 700px;
                    margin: 20px auto;
                    background-color: #ffffff;
                    padding: 20px;
                    border-radius: 10px;
                    box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.1);
                }
                h2 {
                    color: #2c3e50;
                    text-align: center;
                    font-size: 28px;
                    margin-bottom: 20px;
                }
                ul {
                    padding: 0;
                    list-style-type: none;
                }
                li {
                    background-color: #ecf0f1;
                    border-radius: 5px;
                    margin: 10px 0;
                    padding: 15px;
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
                }
                .label {
                    font-weight: bold;
                    color: #2980b9;
                    text-transform: uppercase;
                }
                .content {
                    color: #34495e;
                    font-style: italic;
                }
                .footer {
                    text-align: center;
                    margin-top: 20px;
                    font-size: 12px;
                    color: #7f8c8d;
                }
                .email-footer {
                    font-size: 12px;
                    margin-top: 20px;
                    text-align: center;
                    color: #7f8c8d;
                }
                .btn {
                    display: inline-block;
                    padding: 10px 20px;
                    background-color: #2980b9;
                    color: #ffffff;
                    text-decoration: none;
                    border-radius: 5px;
                    margin-top: 15px;
                }
                .btn:hover {
                    background-color: #3498db;
                }
            </style>
        </head>
        <body>
            <div class="email-wrapper">
                <h2>Database Data</h2>
                <ul>
                    <li>
                        <span class="label">Name:</span> <span class="content">${result.name}</span>
                    </li>
                    <li>
                        <span class="label">Email:</span> <span class="content">${result.email}</span>
                    </li>
                    <li>
                        <span class="label">Message:</span> <span class="content">${result.message}</span>
                    </li>
                    <li>
                        <span class="label">Number:</span> <span class="content">${result.number}</span>
                    </li>
                    <li>
                        <span class="label">Type:</span> <span class="content">${result.type}</span>
                    </li>
                    <li>
                        <span class="label">Date:</span> <span class="content">${result.date}</span>
                    </li>
                </ul>
                <div class="email-footer">
                    <p>This email was generated by your database system.</p>
                    <a class="btn" href="#">View More Details</a>
                </div>
            </div>
        </body>
        </html>
        `;

        // Configure Nodemailer
        const transporter = nodemailer.createTransport({
            host: process.env["EMAIL_HOST"],
            port: process.env["EMAIL_PORT"],
            secure: true,
            auth: {
                user: process.env.EMAIL_USER,
                pass: process.env.EMAIL_PASS,
            },
        });

        // Setup email data
        const mailOptions = {
            from: "perarasup998@gmail.com",
            to: process.env.EMAIL_TO, // Add recipient email here
            subject: 'Database Data',
            html: mailContent, // Use HTML for rich formatting
        };

        // Send email
        transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
                console.error('Error sending email:', error);
            } else {
                console.log('Email sent:', info.response);
            }
        });

    } catch (error) {
        console.error('Error sending email:', error);
    }
};
